// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.4
// source: pb/chat_room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room int32

const (
	Room_F1  Room = 0
	Room_F2  Room = 1
	Room_F3  Room = 2
	Room_F4  Room = 3
	Room_F5  Room = 4
	Room_F6  Room = 5
	Room_F7  Room = 6
	Room_F8  Room = 7
	Room_F9  Room = 8
	Room_F10 Room = 9
	Room_F11 Room = 10
	Room_F12 Room = 11
)

// Enum value maps for Room.
var (
	Room_name = map[int32]string{
		0:  "F1",
		1:  "F2",
		2:  "F3",
		3:  "F4",
		4:  "F5",
		5:  "F6",
		6:  "F7",
		7:  "F8",
		8:  "F9",
		9:  "F10",
		10: "F11",
		11: "F12",
	}
	Room_value = map[string]int32{
		"F1":  0,
		"F2":  1,
		"F3":  2,
		"F4":  3,
		"F5":  4,
		"F6":  5,
		"F7":  6,
		"F8":  7,
		"F9":  8,
		"F10": 9,
		"F11": 10,
		"F12": 11,
	}
)

func (x Room) Enum() *Room {
	p := new(Room)
	*p = x
	return p
}

func (x Room) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Room) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_chat_room_proto_enumTypes[0].Descriptor()
}

func (Room) Type() protoreflect.EnumType {
	return &file_pb_chat_room_proto_enumTypes[0]
}

func (x Room) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Room.Descriptor instead.
func (Room) EnumDescriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{0}
}

type RoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room Room `protobuf:"varint,1,opt,name=room,proto3,enum=Room" json:"room,omitempty"`
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomRequest) GetRoom() Room {
	if x != nil {
		return x.Room
	}
	return Room_F1
}

type RoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddr string    `protobuf:"bytes,1,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	ErrMsg *ErrorMsg `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *RoomResponse) GetErrMsg() *ErrorMsg {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Room Room   `protobuf:"varint,2,opt,name=room,proto3,enum=Room" json:"room,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinRequest) GetRoom() Room {
	if x != nil {
		return x.Room
	}
	return Room_F1
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg *ErrorMsg `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetErrMsg() *ErrorMsg {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type ChatClientMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMil int64    `protobuf:"varint,1,opt,name=unix_mil,json=unixMil,proto3" json:"unix_mil,omitempty"`
	ChatMsg *ChatMsg `protobuf:"bytes,2,opt,name=chat_msg,json=chatMsg,proto3" json:"chat_msg,omitempty"`
}

func (x *ChatClientMsg) Reset() {
	*x = ChatClientMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatClientMsg) ProtoMessage() {}

func (x *ChatClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatClientMsg.ProtoReflect.Descriptor instead.
func (*ChatClientMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{4}
}

func (x *ChatClientMsg) GetUnixMil() int64 {
	if x != nil {
		return x.UnixMil
	}
	return 0
}

func (x *ChatClientMsg) GetChatMsg() *ChatMsg {
	if x != nil {
		return x.ChatMsg
	}
	return nil
}

type ChatServerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMil  int64      `protobuf:"varint,1,opt,name=unix_mil,json=unixMil,proto3" json:"unix_mil,omitempty"`
	ChatMsgs []*ChatMsg `protobuf:"bytes,2,rep,name=chat_msgs,json=chatMsgs,proto3" json:"chat_msgs,omitempty"`
	ErrMsg   *ErrorMsg  `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *ChatServerMsg) Reset() {
	*x = ChatServerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatServerMsg) ProtoMessage() {}

func (x *ChatServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatServerMsg.ProtoReflect.Descriptor instead.
func (*ChatServerMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{5}
}

func (x *ChatServerMsg) GetUnixMil() int64 {
	if x != nil {
		return x.UnixMil
	}
	return 0
}

func (x *ChatServerMsg) GetChatMsgs() []*ChatMsg {
	if x != nil {
		return x.ChatMsgs
	}
	return nil
}

func (x *ChatServerMsg) GetErrMsg() *ErrorMsg {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err bool   `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorMsg) GetErr() bool {
	if x != nil {
		return x.Err
	}
	return false
}

func (x *ErrorMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_chat_room_proto protoreflect.FileDescriptor

var file_pb_chat_room_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x4b,
	0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x3c, 0x0a, 0x0b, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x32, 0x0a, 0x0c, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x4f, 0x0a,
	0x0d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x75, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x08, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x75,
	0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67,
	0x73, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2e, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x69, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x31, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x32, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x33, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x34, 0x10, 0x03, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x35, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x36, 0x10, 0x05, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x37, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x38, 0x10, 0x07, 0x12, 0x06,
	0x0a, 0x02, 0x46, 0x39, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x31, 0x30, 0x10, 0x09, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x31, 0x31, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x31, 0x32, 0x10,
	0x0b, 0x32, 0x32, 0x0a, 0x0b, 0x4c, 0x6f, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0c, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x62, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e,
	0x12, 0x0c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_chat_room_proto_rawDescOnce sync.Once
	file_pb_chat_room_proto_rawDescData = file_pb_chat_room_proto_rawDesc
)

func file_pb_chat_room_proto_rawDescGZIP() []byte {
	file_pb_chat_room_proto_rawDescOnce.Do(func() {
		file_pb_chat_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_chat_room_proto_rawDescData)
	})
	return file_pb_chat_room_proto_rawDescData
}

var file_pb_chat_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_chat_room_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_chat_room_proto_goTypes = []interface{}{
	(Room)(0),             // 0: Room
	(*RoomRequest)(nil),   // 1: RoomRequest
	(*RoomResponse)(nil),  // 2: RoomResponse
	(*JoinRequest)(nil),   // 3: JoinRequest
	(*JoinResponse)(nil),  // 4: JoinResponse
	(*ChatClientMsg)(nil), // 5: ChatClientMsg
	(*ChatServerMsg)(nil), // 6: ChatServerMsg
	(*ChatMsg)(nil),       // 7: ChatMsg
	(*ErrorMsg)(nil),      // 8: ErrorMsg
}
var file_pb_chat_room_proto_depIdxs = []int32{
	0,  // 0: RoomRequest.room:type_name -> Room
	8,  // 1: RoomResponse.err_msg:type_name -> ErrorMsg
	0,  // 2: JoinRequest.room:type_name -> Room
	8,  // 3: JoinResponse.err_msg:type_name -> ErrorMsg
	7,  // 4: ChatClientMsg.chat_msg:type_name -> ChatMsg
	7,  // 5: ChatServerMsg.chat_msgs:type_name -> ChatMsg
	8,  // 6: ChatServerMsg.err_msg:type_name -> ErrorMsg
	1,  // 7: LobyService.Room:input_type -> RoomRequest
	3,  // 8: ChatRoomService.Join:input_type -> JoinRequest
	5,  // 9: ChatRoomService.Chat:input_type -> ChatClientMsg
	2,  // 10: LobyService.Room:output_type -> RoomResponse
	4,  // 11: ChatRoomService.Join:output_type -> JoinResponse
	6,  // 12: ChatRoomService.Chat:output_type -> ChatServerMsg
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_chat_room_proto_init() }
func file_pb_chat_room_proto_init() {
	if File_pb_chat_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_chat_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatClientMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatServerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_chat_room_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_chat_room_proto_goTypes,
		DependencyIndexes: file_pb_chat_room_proto_depIdxs,
		EnumInfos:         file_pb_chat_room_proto_enumTypes,
		MessageInfos:      file_pb_chat_room_proto_msgTypes,
	}.Build()
	File_pb_chat_room_proto = out.File
	file_pb_chat_room_proto_rawDesc = nil
	file_pb_chat_room_proto_goTypes = nil
	file_pb_chat_room_proto_depIdxs = nil
}
